version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: k3ytoshi
  coins:
  - 1car
  - 2homes
  - 1000atom
  - 1000etch
  - 2btc
  mnemonic: garage rebel spread page ozone praise false trick pill cool tattoo roast
- name: Glenn
  coins:
  - 1car
  - 2homes
  - 1000atom
  - 1000eth
  - 2btc
  mnemonic:
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ts-client
  hooks:
    path: react/src/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
genesis: 
  chain_id: lifedefied
